namespace MilkMatrix.Milk.Models.Response.ConfigSettings
{
    public class ConfigSettingResponse
    {
        public int? BusinessId { get; set; }
        public string UnitType { get; set; }
        public int? UnitId { get; set; }
        public int? genl_can_per_lit { get; set; }
        public int? genl_can_war_thr { get; set; }
        public decimal? genl_ltr_to_kg_con_fac { get; set; }
        public bool? genl_wei_rou_mod { get; set; }
        public bool? genl_qua_rou_mod { get; set; }
        public string genl_mem_qua_mod { get; set; }
        public string genl_bmc_qua_mod { get; set; }
        public bool? genl_use_def_snf { get; set; }
        public decimal? genl_def_snf_val { get; set; }
        public bool? genl_zer_rat_all { get; set; }
        public bool? genl_ena_shi_wis_ent_dat { get; set; }
        public decimal? qcdl_col_min_fat { get; set; }
        public decimal? qcdl_col_max_fat { get; set; }
        public decimal? qcdl_col_min_snf { get; set; }
        public decimal? qcdl_col_max_snf { get; set; }
        public string qcdl_dis_qty_mod { get; set; }
        public decimal? qcdl_dis_ltr_kg { get; set; }
        public decimal? qcdl_dis_min_fat { get; set; }
        public decimal? qcdl_dis_max_fat { get; set; }
        public decimal? qcdl_dis_min_snf { get; set; }
        public decimal? qcdl_dis_max_snf { get; set; }
        public string dval_mil_typ_dva { get; set; }
        public decimal? dval_def_fat { get; set; }
        public decimal? dval_def_snf { get; set; }
        public bool? wset_is_act_wse { get; set; }
        public string wset_wei_rou_by { get; set; }
        public string wset_can_ave_wei { get; set; }
        public int? lset_tra_siz { get; set; }
        public bool? lset_snf_rou { get; set; }
        public string lset_snf_rou_by { get; set; }
        public int? lset_snf_aft_dec { get; set; }
        public string lset_snf_for { get; set; }
        public decimal? lset_snf_con { get; set; }
        public bool? lset_fat_rou { get; set; }
        public string lset_fat_rou_by { get; set; }
        public int? lset_fat_aft_dec { get; set; }
        public bool? lset_lr_rou { get; set; }
        public string lset_lr_rou_by { get; set; }
        public int? lset_lr_aft_dec { get; set; }
        public string qlmt_mil_typ_qlm { get; set; }
        public decimal? qlmt_min_fat { get; set; }
        public decimal? qlmt_max_fat { get; set; }
        public decimal? qlmt_min_snf { get; set; }
        public decimal? qlmt_max_snf { get; set; }
        public decimal? qlmt_min_clr { get; set; }
        public decimal? qlmt_max_clr { get; set; }
        public string adlt_tes_nam { get; set; }
        public bool? adlt_is_ena_adl { get; set; }
        public bool? func_all_far_cod_edi { get; set; }
        public bool? func_val_rat_ran_on_imp { get; set; }
        public bool? func_loa_all_rou_on_doc { get; set; }
        public bool? func_all_dup_far_col { get; set; }
        public bool? func_ena_pay_cyc { get; set; }
        public string unit_bmc_col_mod { get; set; }
        public string unit_mpp_col_mod { get; set; }
        public decimal? unit_lit_to_kg_con { get; set; }
        public decimal? unit_kg_to_lit_con { get; set; }
        public string entr_mul_sam_typ { get; set; }
        public string entr_mul_dif_typ { get; set; }
        public string inpt_inp_fat { get; set; }
        public string inpt_inp_snf { get; set; }
        public string inpt_inp_clr { get; set; }
        public string inpt_inp_pro { get; set; }
        public string inpt_inp_lac { get; set; }
        public string inpt_inp_wat { get; set; }
        public decimal? vari_var_fat { get; set; }
        public bool? vari_blo_fat { get; set; }
        public decimal? vari_var_snf { get; set; }
        public bool? vari_blo_snf { get; set; }
        public decimal? vari_var_qty { get; set; }
        public bool? vari_blo_qty { get; set; }
        public string mach_mac_bas_on { get; set; }
        public string mach_mac_shi { get; set; }
        public string mach_mac_no { get; set; }
        public string dspl_dis_bas_on { get; set; }
        public string dspl_dis_shi { get; set; }
        public string dspl_dis_no { get; set; }
        public bool? othr_is_aut_mer { get; set; }
        public int? othr_rat_cha_app { get; set; }
        public bool is_deleted { get; set; }
        public int? created_by { get; set; }
        public DateTime created_on { get; set; }
        public int? modified_by { get; set; }
        public DateTime? modified_on { get; set; }
    }
}
